# Generated by Django 3.2 on 2022-09-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_specialization_consultation_price'),
        ('patients', '0003_application_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='specialization',
        ),
        migrations.AddField(
            model_name='application',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
