# Generated by Django 3.2 on 2022-10-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_ticketmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmedia',
            name='file',
            field=models.FileField(max_length=300, upload_to=''),
        ),
    ]
