# Generated by Django 3.2 on 2022-10-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_ticketmedia_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_identifier',
        ),
        migrations.AddField(
            model_name='application',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
