# Generated by Django 3.2 on 2022-10-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_application_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='identifier',
            new_name='checkoutID',
        ),
        migrations.AddField(
            model_name='application',
            name='merchantID',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
