# Generated by Django 3.2 on 2022-10-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20221017_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.application'),
        ),
    ]
