# Generated by Django 3.2 on 2022-09-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.specialization'),
        ),
    ]
