# Generated by Django 3.2 on 2022-09-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20220926_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='consultation_price',
            field=models.FloatField(default=1000),
        ),
    ]
