# Generated by Django 3.2 on 2022-10-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
